AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'ModelGuard MVP - Core Artifact Management API'

Parameters:
  DeploymentRegion:
    Type: String
    Default: us-east-2
    Description: AWS region for deployment
    AllowedValues:
      - us-east-1
      - us-east-2

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 512  # MB of RAM (also sets /tmp to 512MB)
    Environment:
      Variables:
        LOG_LEVEL: INFO  # Change to DEBUG for verbose logging
        PYTHONPATH: /var/task:/var/task/src
        ARTIFACTS_TABLE: !Ref ArtifactsTable
        ARTIFACTS_BUCKET: !Ref ArtifactsBucket
        BEDROCK_MODEL_ID: anthropic.claude-haiku-4-5-20251001-v1:0
        BEDROCK_REGION: !Ref DeploymentRegion
        USER_POOL_ID: !Ref ModelGuardUserPool
        USER_POOL_CLIENT_ID: !Ref ModelGuardUserPoolClient
        TOKENS_TABLE: !Ref TokensTable
    Tracing: Active

Resources:
  ###########################################################
  # DynamoDB Tables
  ###########################################################
  ArtifactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ModelGuard-Artifacts-Metadata
      BillingMode: PAY_PER_REQUEST  # On-demand pricing
      AttributeDefinitions:
        - AttributeName: artifact_id
          AttributeType: S
      KeySchema:
        - AttributeName: artifact_id
          KeyType: HASH  # Primary key
      Tags:
        - Key: Project
          Value: ModelGuard
      SSESpecification: # Set server-side encryption to use AWS owned key (free)
        SSEEnabled: false

  TokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ModelGuard-Tokens
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      Tags:
        - Key: Project
          Value: ModelGuard
      SSESpecification: # Set server-side encryption to use AWS owned key (free)
        SSEEnabled: false

  ###########################################################
  # S3 Artifact Storage
  ###########################################################
  ArtifactsLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'modelguard-artifacts-logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: ModelGuard
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1
            Prefix: "access-logs/"
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 #(free)

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'modelguard-artifacts-files'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref ArtifactsLogBucket
        LogFilePrefix: "access-logs/"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 #(free)
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Project
          Value: ModelGuard

  ###########################################################
  # Frontend Deployment
  ############################################################
  FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256 #(free)
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        VersioningConfiguration:
          Status: Suspended

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: FrontendOAC
        Description: OAC for static site
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: FrontendOrigin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: FrontendOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
  
  ###########################################################
  # Cognito User Pool + Client + Domain + Groups
  ###########################################################
  ModelGuardUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ModelGuard-Users
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      UserPoolTags:
        Project: ModelGuard

  ModelGuardUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ModelGuardUserPool
      ClientName: ModelGuard-Web-Client
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH

  ModelGuardUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref ModelGuardUserPool
      Domain: !Sub 'modelguard-${AWS::AccountId}'

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref ModelGuardUserPool
      GroupName: Admin
      Description: Full access to all artifacts and operations
      Precedence: 1

  UserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref ModelGuardUserPool
      GroupName: User
      Description: Standard user access to artifacts
      Precedence: 2

  ###########################################################
  # API Gateway + Cognito Authorizer
  ###########################################################
  ModelGuardApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Description: ModelGuard MVP API
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Authorization,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt ModelGuardUserPool.Arn

  ###########################################################
  # Lambda: /authenticate (no authorizer)
  ###########################################################
  AuthenticateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.authenticate.lambda_handler
      Description: User authentication
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        AuthenticateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /authenticate
            Method: PUT
            Auth:
              Authorizer: NONE

  ###########################################################
  # Lambda Functions for Artifact Endpoints
  ###########################################################
  # POST /artifacts - Enumerate artifacts
  PostArtifactsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.post_artifacts.lambda_handler
      Description: Enumerate/List artifacts from registry
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        ListArtifacts:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /artifacts
            Method: POST

  # POST /artifact/{artifact_type} - Upload artifact
  PostArtifactUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.post_artifact_upload.lambda_handler
      Description: Upload/Create new artifact
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        CreateArtifact:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /artifact/{artifact_type}
            Method: POST

  # GET /artifacts/{artifact_type}/{id} - Download artifact
  GetArtifactDownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.get_artifact_download.lambda_handler
      Description: Download/Retrieve artifact by type and ID
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        GetArtifact:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /artifacts/{artifact_type}/{id}
            Method: GET

  # PUT /artifacts/{artifact_type}/{id} - Update artifact
  PutArtifactUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.put_artifact_update.lambda_handler
      Description: Update existing artifact
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        UpdateArtifact:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /artifacts/{artifact_type}/{id}
            Method: PUT

  # GET /artifact/byName/{name} - Search by name
  GetSearchByNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.get_search_by_name.lambda_handler
      Description: Search artifacts by name
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        SearchByName:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /artifact/byName/{name}
            Method: GET

  # POST /artifact/byRegEx - Search by regex
  PostSearchByRegexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.post_search_by_regex.lambda_handler
      Description: Search artifacts using regular expressions
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        SearchByRegex:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /artifact/byRegEx
            Method: POST

  # GET /artifact/model/{id}/rate - Rate model
  GetModelRateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.get_model_rate.lambda_handler
      Description: Get ratings for model artifacts
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        ModelRate:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /artifact/model/{id}/rate
            Method: GET

  # DELETE /reset - Reset system
  DeleteResetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas.delete_reset.lambda_handler
      Description: Reset system to default state
      Role: arn:aws:iam::378950442938:role/BasicLambdaRole
      Events:
        Reset:
          Type: Api
          Properties:
            RestApiId: !Ref ModelGuardApi
            Path: /reset
            Method: DELETE

Outputs:
  ModelGuardApiUrl:
    Description: API Gateway endpoint URL for testing
    Value: !Sub 'https://${ModelGuardApi}.execute-api.${DeploymentRegion}.amazonaws.com/dev/'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  ArtifactsTableName:
    Description: DynamoDB table for model metadata
    Value: !Ref ArtifactsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  ArtifactsBucketName:
    Description: S3 bucket for model/code/dataset storage
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref ModelGuardUserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref ModelGuardUserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  CognitoDomain:
    Description: Cognito Domain for authentication
    Value: !Sub 'https://${ModelGuardUserPoolDomain}.auth.${DeploymentRegion}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-CognitoDomain'

  FrontendBucket:
    Description: "S3 bucket to host frontend"
    Value: !Ref FrontendBucket

  CloudFrontDistribution:
    Description: "CloudFront distribution ID for the frontend"
    Value: !Ref CloudFrontDistribution
